Almost done
zavtra-na-rabotu/gophermart pull request #3
Opened 2024-07-27 17:29 UTC by zavtra-na-rabotu

2024-08-01 21:37 UTC, avhitrov requested changes
Спроектировано все довольно грамотно, но есть ошибки при оформлении работы с БД и хочется видеть более внятную обработку кейса с TooManyRequests.

2024-08-01 21:37 UTC, avhitrov commented on internal/db/repository/order.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
    return nil, err
}
```

2024-08-01 21:37 UTC, avhitrov commented on internal/db/repository/order.go
> +	}
rows.Err()

2024-08-01 21:37 UTC, avhitrov commented on internal/db/repository/withdrawal.go
> +	}
rows.Err()

2024-08-01 21:37 UTC, avhitrov commented on internal/job/accrual.go
> +		}
При получении StatusTooManyRequests надо, как минимум, подождать положенное количество секунд (в ТЗ есть) прежде, чем продолжать долбить сервис запросами. А в идеале перезапросить данные по заказу по прошествии этих секунд.

2024-08-08 21:42 UTC, zavtra-na-rabotu commented on internal/job/accrual.go
> +		}
Теперь пытаюсь достать нужное время для ожидания из Retry-After заголовка, если не получается, то ожидаем минуту по умолчанию.

2024-08-12 18:42 UTC, avhitrov approved these changes
Замечания исправлены. Аппрув.

2024-12-09 09:36 UTC, merged